[package]
name = "hantu"
version = "0.1.0"
authors = ["C.K. <admin@0x434b.dev>"]
repository = "https://github.com/0xricksanchez/hantu/"
edition = "2021"


[dependencies]
log = "*"

[profile.release]
debug = true 
lto = "fat"
panic = "abort"
codegen-units = 1
opt-level = "z"
